apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fastapi-rules
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: fastapi.rules
    rules:
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m]))
            / sum(rate(http_requests_total[5m])) > 0.05
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "FastAPI: High 5xx error rate detected"
        description: "The 5xx error rate has exceeded 5% over the last 5 minutes."