apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-servicemonitor
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
      scheme: http