name: CI - Build, Scan, SBOM
on: [push, pull_request]


env:
  IMAGE: ozdemire/fastapi-app
  TAG: latest

jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
          platforms: linux/amd64,linux/arm64

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}:${{ env.TAG }}
          format: table
          output: trivy-report.txt
          exit-code: '0'

      - name: Install syft & bandit
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s --
          pipx install bandit

      - name: SBOM (syft)
        run: ./bin/syft ${{ env.IMAGE }}:${{ env.TAG }} -o json > sbom.json

      - name: Bandit (static code)
        run: bandit -r app/ -f json -o bandit-report.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            trivy-report.txt
            sbom.json
            bandit-report.json
      - name: Sign Docker image with Cosign
        run: cosign sign --key $COSIGN_KEY ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      - name: Verify signed image
        run: cosign verify --key cosign.pub ${{ env.IMAGE_NAME }}:${{ env.TAG }}